baseURL: "https://runbooks.prometheus-operator.dev"
languageCode: "en-us"
title: "kube-prometheus runbooks"

theme: book

params:
  BookRepo: "https://github.com/prometheus-operator/runbooks"
  BookEditPath: "edit/main"
  BookSearch: true
  BookSection: "runbooks"
  #BookMenuBundle: "/menu"

markup:
  goldmark:
    renderer:
      # Allows rendering HTML tags. This would only be truly "unsafe" if we were accepting untrusted user input and rendering it, which we aren't.
      unsafe: true
