baseURL: "https://runbooks.thaum.xyz"
languageCode: "en-us"
title: "kube-prometheus runbooks"

theme: book

params:
  BookRepo: "https://github.com/paulfantom/runbooks"
  BookEditPath: "edit/main"
  BookSearch: true
  BookSection: "runbooks"
  #BookMenuBundle: "/menu"

